language: python
sudo: false
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial          # required for Python >= 3.7
    - python: 3.8
      env: TOXENV=py38
      dist: xenial          # required for Python >= 3.7
install:
  # tox is pinned for python 3.4 support
  - travis_retry pip install tox==3.14.0
script:
  - travis_retry tox
